# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '29 23 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tests
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    
    - uses: azure/login@v1
      with:
        creds: '{"clientId":"${{ secrets.TERRATEST_CLIENT_ID }}","clientSecret":"${{ secrets.TERRATEST_CLIENT_SECRET }}","subscriptionId":"${{ secrets.TERRATEST_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TERRATEST_TENANT_ID }}"}'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...