name: Terratest End-End Tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '29 23 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tests
    env:
      ARM_CLIENT_ID: ${{ secrets.TERRATEST_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.TERRATEST_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.TERRATEST_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.TERRATEST_TENANT_ID }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Test
      run: go test -v -timeout 30m